name: Feedback

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  feedback:
    if: github.event.pull_request.merged == true
    uses: kubestellar/infra/.github/workflows/reusable-feedback.yml@main
    secrets: inherit
